#!/bin/sh
# run command line in the specified docker image, using options
# that are needed by fuse and therefore, fs123
if test $# = 0 -o x"$1" = x"-h" -o x"$1" = x"--help"; then
  echo "Usage: $0 [DOCKER_ARGS] DOCKER_IMAGE" >&2
  exit 1
fi
set -eux
docker run  \
  --mount=type=bind,src=$(pwd -P),destination=/fs123 --device /dev/fuse \
  --cap-add SYS_PTRACE --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
  "$@"
