#!/bin/bash

# See README for assumptions made by all the t-* tests
# in this directory.

die(){
    1>&2 echo "$@"
    exit 1
}

trap 'echo 1>&2 $0: Exiting on ERR trap, line: $LINENO; exit 1' ERR

cache=$(readlink -f "$MTPT/../cachedir")
stat $MTPT # make sure there's something in the cache!
sleep 1 # serializing is asynchronous, so let's give it a chance to catch up.
if test ! -d "$cache/0"; then
	echo "$0: cache \"$cache\" does not seem to exist or is not populated" >&2
	exit 1
fi
exec fs123p7 cachedump $(find "$cache" -type f -not -name 'stats*' -print| head -1)
