---
language: minimal
sudo: required

services:
    - docker

deploy:
    provider: releases
    api_key:
        secure: "UYxJTTcSmL6LcEpmW4YjR91MUsQeprHcLbe10C4ps/nSmlKEHvjE+IObJbl1SVPs2/zFYlOhlSIegpAxedgU+dh49zmgiVj4ArgHRX4bKh7U7MVPsEnGuIlsEipfjpBsddmui1xSY8FM2anQ5fEWYSFOOL1DSmZ/5LJd+cJnBjnyAnU1MkS2xbLIJju4fVSmwiZ5Y9XrFZ0OqFNDxL3NWWMTQLOjnxwuK1kda6rAhami3B/94+mbQPx+7tzQTSifLswZgm4lTCEbpezr5YWj+WZ2AQ/Gs5CTEmLbH4J7uEBYj1BDcqVQxp8R8IfU/iZuyOvbv1HbO50S0foq6T7EbJOHUUaMN2i/uB9QEM2IJfmiBoTySiDY4ubvG0BzY5Hi5Nz122d+TPele9wv3/Fio6SykLboNl0/r9Ik7TniVLLMnilUMvxMLvEuhAVm68lnOg5aO9u8I5YLiBURo1bOJ2GJTDPdfsZ2ffrEQzV+1OYjK2dgbJPVPJIMe2y4+QTatQ/eUFOYYh/TA7doKPNFHEZA/3P9uW1HXnXReXQE0vktiMJ6J0KLKXMouCXoK47hd6mhKYVuGsQELh8XblkX5jsJGV+u2jFEtvAIBUk0Ts2t6cGgZh7Ku9Lz0wMUER1xLiUFyQ6HisFYfxs1Odb07p7ZbwWcGDmpwxrfLyTAJfk="
    file: "placeholder"
    skip_cleanup: true
    draft: true
    on:
        tags: true

# alpine 3.12 (or later) is built static, while 3.11 is dynamic
env:
    - DOCKER_IMAGE=alpine:3.11
    - DOCKER_IMAGE=alpine:3.12
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:32
    - DOCKER_IMAGE=ubuntu:bionic
    - DOCKER_IMAGE=ubuntu:xenial
    - DOCKER_IMAGE=debian:stretch
    - DOCKER_IMAGE=debian:buster

# add fuse to the build host VM
# https://github.com/travis-ci/travis-ci/issues/1100
before_install:
    - sudo apt-get install -qq pkg-config fuse
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf

install:
    - docker pull $DOCKER_IMAGE

script:
    - > 
        ./misc/dockrun ${DOCKER_IMAGE} 
	/bin/sh -e -c "cd /fs123 && . ./misc/prereqs.${DOCKER_IMAGE} && make -j4 check && make -j4 core123-check && make install"

# There must be a better way ...
after_failure:
    - cat s/fs123.diag
    - cat s/errorlog.1 s/errorlog
    - cat s/exportd.*
    - cat c/fs123.diag
    - cat c/fs123.err
    - cat c/fs123.exstatus

# vim: ts=4:sw=4:et:ai
