---
language: minimal
sudo: required

services:
    - docker

env:
    - DOCKER_IMAGE=alpine:3.9
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:29
    - DOCKER_IMAGE=ubuntu:bionic
    - DOCKER_IMAGE=ubuntu:xenial

# add fuse to the build host VM
# https://github.com/travis-ci/travis-ci/issues/1100
before_install:
    - sudo apt-get install -qq pkg-config fuse
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf

install:
    - docker pull $DOCKER_IMAGE

script:
    - > 
        docker run 
        --mount=type=bind,src=$(pwd -P),destination=/fs123
        --device /dev/fuse --cap-add SYS_PTRACE --cap-add SYS_ADMIN
        ${DOCKER_IMAGE}
        /bin/sh -c "cd /fs123 && . ./misc/prereqs.${DOCKER_IMAGE} && make && make check && make install"

# vim: ts=4:sw=4:et:ai
